SELECT * FROM Products --FINDING INFO FROM THE DBASE
SELECT --REMOVED THE ASTERISK
ProductID, --SELECTED EACH PRODUCT LINE REQUIRED
ProductName,
UnitPrice,
UnitsInStock -- NO COMMA ON LAST SELECTION
FROM Products -- SELECT ALL QUERIES AND F5 TO RUN